DELETE http://localhost:3001/api/exams/6365315e23230d8e725e8171
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjUzMTNjMjMyMzBkOGU3MjVlODE2ZCIsInVzZXJuYW1lIjoicGVjaG9ob3QiLCJpYXQiOjE2Njc1NzYxMzl9.RPnsaB_No9aAWMqAMNEnO3F0fuA5AtaxtC8ak6ZI88s